# Generated by Django 4.2.11 on 2024-07-17 08:59

from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields
import openforms.appointments.contrib.openafspraak.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("zgw_consumers", "0020_service_timeout"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenAfspraakConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "required_customer_fields",
                    django_jsonform.models.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("public_id", "Public ID"),
                                ("first_name", "First name"),
                                ("last_name", "Last name"),
                                ("email", "Email address"),
                                ("phone", "Phone number"),
                                ("address", "Address"),
                                ("city", "City"),
                                ("postal_code", "Postal code"),
                                ("date_of_birth", "Birthday"),
                            ],
                            max_length=50,
                        ),
                        default=openforms.appointments.contrib.openafspraak.models.get_default_customer_fields,
                        help_text="Select the customer fields for the contact details step. Fields that you select here are REQUIRED fields for the user making the appointment. You must have at least one field to be able to identify the customer.",
                        size=None,
                        verbose_name="Required customer fields",
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        help_text="The OpenAfspraak API. Example: https://example.com:8443/api/v1/",
                        limit_choices_to={"api_type": "orc"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="zgw_consumers.service",
                        verbose_name="Calendar API",
                    ),
                ),
            ],
            options={
                "verbose_name": "OpenAfspraak configuration",
            },
        ),
    ]
